server:
  port: 8080
spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    open-in-view: false
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog.yaml
    default-schema: public

  logging:
    level:
      liquibase: debug